-- MySQL Script generated by MySQL Workbench
-- 05/07/15 01:59:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tim3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tim3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tim3` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Tim3` ;

-- -----------------------------------------------------
-- Table `Tim3`.`TipRadnogMjesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`TipRadnogMjesta` (
  `idTipRadnogMjesta` INT NOT NULL,
  `radnoMjesto` VARCHAR(10) NULL,
  PRIMARY KEY (`idTipRadnogMjesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`Radnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`Radnik` (
  `idRadnik` INT NOT NULL,
  `ime` VARCHAR(10) NULL,
  `prezime` VARCHAR(10) NULL,
  `JMBG` VARCHAR(10) NULL,
  `tipRadnogMjesta` INT NOT NULL,
  PRIMARY KEY (`idRadnik`),
  INDEX `tipRadnogMjesta_idx` (`tipRadnogMjesta` ASC),
  CONSTRAINT `tipRadnogMjesta`
    FOREIGN KEY (`tipRadnogMjesta`)
    REFERENCES `Tim3`.`TipRadnogMjesta` (`idTipRadnogMjesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`Autobus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`Autobus` (
  `idAutobus` INT NOT NULL,
  `model` VARCHAR(10) NULL,
  `kapacitet` INT NULL,
  `registracija` VARCHAR(10) NULL,
  PRIMARY KEY (`idAutobus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`AutobuskaLinija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`AutobuskaLinija` (
  `idLinija` INT NOT NULL,
  `brojLinije` INT NULL,
  `polaziste` VARCHAR(10) NULL,
  `odrediste` VARCHAR(10) NULL,
  `datumPolaska` DATETIME NULL,
  `vrijemePolaska` DATETIME NULL,
  `peron` INT NULL,
  `distanca` DOUBLE NULL,
  `trajanje` DOUBLE NULL,
  `cijenaJednosmjerne` DOUBLE NULL,
  `cijenaDvosmjerne` DOUBLE NULL,
  `medjunarodna` TINYINT(1) NULL,
  `autobus` INT NULL,
  `vozac` INT NULL,
  PRIMARY KEY (`idLinija`),
  INDEX `autobus_idx` (`autobus` ASC),
  INDEX `vozac_idx` (`vozac` ASC),
  CONSTRAINT `autobus`
    FOREIGN KEY (`autobus`)
    REFERENCES `Tim3`.`Autobus` (`idAutobus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vozac`
    FOREIGN KEY (`vozac`)
    REFERENCES `Tim3`.`Radnik` (`idRadnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`Nalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`Nalog` (
  `idNalog` INT NOT NULL,
  `datumPolaska` DATETIME NULL,
  `vrijemePolaska` DATETIME NULL,
  `linija` INT NULL,
  PRIMARY KEY (`idNalog`),
  INDEX `linija_idx` (`linija` ASC),
  CONSTRAINT `linija`
    FOREIGN KEY (`linija`)
    REFERENCES `Tim3`.`AutobuskaLinija` (`idLinija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`TipKorisnickogRacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`TipKorisnickogRacuna` (
  `idTipKorisnickogRacuna` INT NOT NULL,
  `naziv` VARCHAR(10) NULL,
  PRIMARY KEY (`idTipKorisnickogRacuna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`KorisnickiRacun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`KorisnickiRacun` (
  `idKorisnickiRacun` INT NOT NULL,
  `korisnickoIme` VARCHAR(10) NULL,
  `sifra` VARCHAR(10) NULL,
  `tipKorisnickogRacuna` INT NULL,
  `radnik` INT NULL,
  PRIMARY KEY (`idKorisnickiRacun`),
  INDEX `radnik_idx` (`radnik` ASC),
  INDEX `tipKorisnickogRacuna_idx` (`tipKorisnickogRacuna` ASC),
  CONSTRAINT `radnik`
    FOREIGN KEY (`radnik`)
    REFERENCES `Tim3`.`Radnik` (`idRadnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipKorisnickogRacuna`
    FOREIGN KEY (`tipKorisnickogRacuna`)
    REFERENCES `Tim3`.`TipKorisnickogRacuna` (`idTipKorisnickogRacuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`TipKarte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`TipKarte` (
  `idTipKarte` INT NOT NULL,
  `tip` VARCHAR(10) NULL,
  PRIMARY KEY (`idTipKarte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`Karta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`Karta` (
  `idKarta` INT NOT NULL,
  `odrediste` VARCHAR(10) NULL,
  `vrijemePolaska` DATETIME NULL,
  `cijena` DOUBLE NULL,
  `tipKarte` INT NULL,
  PRIMARY KEY (`idKarta`),
  INDEX `tipKarte_idx` (`tipKarte` ASC),
  CONSTRAINT `tipKarte`
    FOREIGN KEY (`tipKarte`)
    REFERENCES `Tim3`.`TipKarte` (`idTipKarte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`MedjunarodnaKarta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`MedjunarodnaKarta` (
  `idMedjunarodna` INT NOT NULL,
  `odrediste` VARCHAR(10) NULL,
  `vrijemePolaska` DATETIME NULL,
  `cijena` DOUBLE NULL,
  `imePutnika` VARCHAR(10) NULL,
  `prezimePutnika` VARCHAR(10) NULL,
  `tipKarte` INT NULL,
  PRIMARY KEY (`idMedjunarodna`),
  INDEX `tipKarte_idx` (`tipKarte` ASC),
  CONSTRAINT `tipMedjunarodneKarte`
    FOREIGN KEY (`tipKarte`)
    REFERENCES `Tim3`.`TipKarte` (`idTipKarte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tim3`.`Rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tim3`.`Rezervacija` (
  `idRezervacija` INT NOT NULL,
  `odrediste` VARCHAR(10) NULL,
  `vrijemePolaska` DATETIME NULL,
  `cijena` DOUBLE NULL,
  `tipKarte` INT NULL,
  PRIMARY KEY (`idRezervacija`),
  INDEX `tipKarte_idx` (`tipKarte` ASC),
  CONSTRAINT `tipRezervacijeKarte`
    FOREIGN KEY (`tipKarte`)
    REFERENCES `Tim3`.`TipKarte` (`idTipKarte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'EtfSI2014' IDENTIFIED BY '2014SIEtf';

GRANT ALL ON `Tim3`.* TO 'EtfSI2014';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
